# -*- coding: utf-8 -*-
"""NEF Project v.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUQOdakh6-_sduku8j5X6K6iWMTc_8Uu

# Create acs_poverty_income.csv
"""

import requests
import pandas as pd

# ACS 5-year dataset
YEAR = "2022"   # Use the most recent ACS available
BASE_URL = f"https://api.census.gov/data/{YEAR}/acs/acs5/subject"

params = {
    "get": "S1701_C03_001E,S1901_C01_012E,NAME",
    "for": "zip code tabulation area:*"
}

response = requests.get(BASE_URL, params=params)
data = response.json()

# Convert to DataFrame
df = pd.DataFrame(data[1:], columns=data[0])

# Rename fields
df = df.rename(columns={
    "S1701_C03_001E": "poverty_rate",
    "S1901_C01_012E": "median_income",
    "zip code tabulation area": "zcta"
})

# Convert numeric fields
df["poverty_rate"] = pd.to_numeric(df["poverty_rate"], errors="coerce")
df["median_income"] = pd.to_numeric(df["median_income"], errors="coerce")

# Keep only necessary fields
df = df[["zcta", "poverty_rate", "median_income"]]

df.to_csv("acs_poverty_income.csv", index=False)

print("Created acs_poverty_income.csv!")

"""# Create acs_population_area.csv"""

"""
Creates acs_population_area.csv for all ZCTAs in the U.S. using:
- ACS 2022 5-year DP05 (total population)
- TIGER/Line 2023 ZCTA shapefile (land area)

Output columns:
- zcta
- population
- land_area_sq_miles
- population_density
"""

import requests
import pandas as pd
import geopandas as gpd

# --------------------------
# CONFIGURATION
# --------------------------
ACS_YEAR = "2022"
ACS_BASE = f"https://api.census.gov/data/{ACS_YEAR}/acs/acs5/profile"

def get_acs_population():
    """
    Fetch total population for all ZCTAs from ACS DP05 (2022).
    Uses DP05_0001E: Estimate!!Total population
    """
    params = {
        "get": "DP05_0001E,NAME",
        "for": "zip code tabulation area:*"
    }

    print("Requesting ACS 2022 population data for all ZCTAs...")
    response = requests.get(ACS_BASE, params=params)

    if response.status_code != 200:
        raise RuntimeError(f"ACS API request failed: {response.status_code} {response.text}")

    data = response.json()
    df = pd.DataFrame(data[1:], columns=data[0])

    # Clean up and rename
    df = df.rename(columns={
        "DP05_0001E": "population",
        "zip code tabulation area": "zcta"
    })

    df["zcta"] = df["zcta"].astype(str).str.zfill(5)
    df["population"] = pd.to_numeric(df["population"], errors="coerce")

    print(f"Retrieved population for {len(df)} ZCTAs.")
    return df[["zcta", "population"]]


def get_land_area_from_shapefile(shapefile_path="tl_2022_us_zcta520.shp"):
    """
    Load TIGER/Line ZCTA shapefile and compute land area in square miles.
    Uses an equal-area projection (EPSG:2163) for accurate area calc.
    """
    print(f"Loading ZCTA shapefile from {shapefile_path} ...")
    zcta_geo = gpd.read_file(shapefile_path)

    # Ensure consistent ZCTA code formatting
    zcta_geo["ZCTA5CE20"] = zcta_geo["ZCTA5CE20"].astype(str).str.zfill(5)

    # Project to an equal-area CRS (US National Atlas Equal Area)
    print("Reprojecting to EPSG:2163 for area calculations...")
    zcta_geo = zcta_geo.to_crs(epsg=2163)

    # Area in square meters, convert to square miles
    # 1 square meter = 3.861021585424458e-7 square miles
    SQM_TO_SQMI = 3.861021585424458e-7
    zcta_geo["land_area_sq_miles"] = zcta_geo["geometry"].area * SQM_TO_SQMI

    land_area_df = zcta_geo[["ZCTA5CE20", "land_area_sq_miles"]].rename(
        columns={"ZCTA5CE20": "zcta"}
    )

    print(f"Computed land area for {len(land_area_df)} ZCTAs.")
    return land_area_df


def main():
    # 1. Get population from ACS
    pop_df = get_acs_population()

    # 2. Get land area from TIGER shapefile
    land_df = get_land_area_from_shapefile("tl_2022_us_zcta520.shp")

    # 3. Merge population + land area
    print("Merging population and land area...")
    merged = pop_df.merge(land_df, on="zcta", how="left")

    # 4. Compute population density
    print("Computing population density (people per sq mile)...")
    merged["population_density"] = merged["population"] / merged["land_area_sq_miles"]

    # 5. Save to CSV
    output_file = "acs_population_area.csv"
    merged.to_csv(output_file, index=False)
    print(f"✅ Created {output_file} with {len(merged)} rows.")


if __name__ == "__main__":
    main()

"""# Main Script"""

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

# -----------------------
# Load NEF loan data
# -----------------------
loans = pd.read_csv("nef_loans.csv")
# Clean and format the zip column for merging
loans["zip_zcta"] = pd.to_numeric(loans["zip"], errors="coerce")
loans = loans.dropna(subset=["zip_zcta"])
loans["zip_zcta"] = loans["zip_zcta"].astype(int).astype(str).str.zfill(5)

# -----------------------
# Load ACS poverty + income
# ZCTA, poverty_rate, median_income
# -----------------------
acs = pd.read_csv("acs_poverty_income.csv")
acs["zcta"] = acs["zcta"].astype(str).str.zfill(5)

# -----------------------
# Load ACS population + land area for density
# ZCTA, population, land_area_sq_miles
# -----------------------
dens = pd.read_csv("acs_population_area.csv")
dens["zcta"] = dens["zcta"].astype(str).str.zfill(5)
dens["population_density"] = dens["population"] / dens["land_area_sq_miles"]

# -----------------------
# Load ZCTA shapefile (TIGER/Line)
# -----------------------
zcta_geo = gpd.read_file("tl_2022_us_zcta520.shp")
zcta_geo["ZCTA5CE20"] = zcta_geo["ZCTA5CE20"].astype(str).str.zfill(5)

# Reproject to an equal-area CRS (US National Atlas Equal Area)
zcta_geo = zcta_geo.to_crs(epsg=2163)

# Merge ACS poverty + income with ZCTA geometry
acs_map = zcta_geo.merge(
    acs, left_on="ZCTA5CE20", right_on="zcta", how="left"
)

# Merge population density
acs_map = acs_map.merge(
    dens[["zcta", "population_density"]],
    on="zcta",
    how="left"
)

# Count loans per ZCTA
loan_counts = loans.groupby("zip_zcta").size().reset_index(name="loan_count")

acs_map = acs_map.merge(
    loan_counts,
    left_on="ZCTA5CE20",
    right_on="zip_zcta",
    how="left"
)

acs_map["loan_count"] = acs_map["loan_count"].fillna(0)

# -----------------------
# Generate maps
# -----------------------

# Poverty heatmap
fig, ax = plt.subplots(figsize=(12, 10))
acs_map.plot(
    column="poverty_rate",
    cmap="Reds",
    linewidth=0,
    ax=ax,
    legend=True,
    legend_kwds={"label": "Poverty Rate (%)"}
)
ax.set_title("ACS Poverty Rate by ZCTA", fontsize=16)
ax.axis("off")
plt.tight_layout()
plt.savefig("poverty_heatmap.png", dpi=300)
plt.show()  # <--- show on screen

# Poverty + loans overlay
fig, ax = plt.subplots(figsize=(12, 10))
acs_map.plot(
    column="poverty_rate",
    cmap="Reds",
    linewidth=0,
    ax=ax,
    legend=True,
    legend_kwds={"label": "Poverty Rate (%)"}
)
acs_map[acs_map["loan_count"] > 0].plot(
    ax=ax,
    markersize=acs_map["loan_count"] * 2,
    color="blue",
    alpha=0.6,
    marker="o"
)
ax.set_title("NEF Loan Distribution Overlayed on Poverty Rates", fontsize=16)
ax.axis("off")
plt.tight_layout()
plt.savefig("poverty_loans_overlay.png", dpi=300)
plt.show()  # <--- show on screen

# Median household income heatmap
fig, ax = plt.subplots(figsize=(12, 10))
acs_map.plot(
    column="median_income",
    cmap="Blues",
    linewidth=0,
    ax=ax,
    legend=True,
    legend_kwds={"label": "Median Household Income ($)"}
)
ax.set_title("ACS Median Household Income by ZCTA", fontsize=16)
ax.axis("off")
plt.tight_layout()
plt.savefig("income_heatmap.png", dpi=300)
plt.show()  # <--- show on screen

# Income + loans overlay
fig, ax = plt.subplots(figsize=(12, 10))
acs_map.plot(
    column="median_income",
    cmap="Blues",
    linewidth=0,
    ax=ax,
    legend=True,
    legend_kwds={"label": "Median Household Income ($)"}
)
acs_map[acs_map["loan_count"] > 0].plot(
    ax=ax,
    markersize=acs_map["loan_count"] * 2,
    color="red",
    alpha=0.6,
    marker="o"
)
ax.set_title("NEF Loan Distribution Overlayed on Median Income", fontsize=16)
ax.axis("off")
plt.tight_layout()
plt.savefig("income_loans_overlay.png", dpi=300)
plt.show()  # <--- show on screen

# Population density heatmap + loans overlay
fig, ax = plt.subplots(figsize=(12, 10))
acs_map.plot(
    column="population_density",
    cmap="viridis",
    linewidth=0,
    ax=ax,
    legend=True,
    legend_kwds={"label": "Population Density (people/sq mile)"}
)
acs_map[acs_map["loan_count"] > 0].plot(
    ax=ax,
    markersize=acs_map["loan_count"] * 2,
    color="white",
    alpha=0.7,
    marker="o"
)
ax.set_title("Rural–Urban Distribution: Population Density with NEF Loans", fontsize=16)
ax.axis("off")
plt.tight_layout()
plt.savefig("population_density_loans.png", dpi=300)
plt.show()  # <--- show on screen

print("Maps generated and displayed successfully!")